### ISSUE TITLE
Would this work if 2 clients with 1 CN connect?

### ISSUE THREAD

**Issue by actuallymentor** [rda0/tc-openvpn#2]
Thanks for this excellent script (found your helpful SF post).

Would this script work as intended if one person signs in on say 3 devices with identical configuration files (cert/cn etc)?

Would it throttle per device or per user CN?

Thanks for your time!

Edit: more specific question.

**Comment by rda0** [comment]
Hi @actuallymentor 

The tc filters apply per ip address. I am pretty sure that only one client/ip can use the CN at any time. If you connect from another ip using a CN which is already in use, this one gets disconnected. It is some time ago since I wrote this and I haven't used Openvpn in a while. Please test it and send some feedback, would be interesting.

**Comment by actuallymentor** [comment]
Thanks for your response @rda0

OpenVPN supports multiple clients through one cn using the duplicate-cn server option.

In that scenario, where multiple ips are using one cn, do you expect per ip or per cn throttling?

If you are not sure I'm happy to do some testing in the wild.

**Comment by rda0** [comment]
You are welcome.

Ah yes, now I remember that option `duplicate-cn`. The script is designed to be used with this option disabled. Each client/ip needs to have its own CN. Otherwise the script will not work correctly.

**Comment by actuallymentor** [comment]
Do you have any recommendations on how to make it compatible with `duplicate-cn`?

Networking is not my forte, but with some pointers I could do some digging.

**Comment by rda0** [comment]
What do you want, limit per IP or per CN?
Limiting per IP should not require a lot of changes, while per CN would require to change the TC class hierarchy.

**Comment by actuallymentor** [comment]
I'd like to limit per ip connected to openvpn.

The use case is a config file being shared on multiple devices from multiple networks (wifi, 4g etc) which should result in multiple ips.

Side thought, when limiting per ip 50 unique people on 1 wifi network wold be throttled as 1 ip right? Any way you can think of where tc operates on a per-connection basis?

Thanks for sparring on this!

**Comment by rda0** [comment]
This should be a matter of changing the script on a few lines, something like this:

in `function bwlimit-enable()`:

`echo "$ip" > "$ipdir"/"$cn".ip`
to
`echo "$ip" > "$ipdir"/"${cn}-${ip}".ip`

in `function bwlimit-disable()`:

`[ -e "$ipdir"/"$cn".ip ] && rm "$ipdir"/"$cn".ip`
to
`[ -e "$ipdir"/"${cn}-${ip}".ip ] && rm "$ipdir"/"${cn}-${ip}".ip`

and:

```
      update)
        [ -z "$2" ] && echo "$0 $1: missing argument [client-CN]" >&2 && exit 1
        [ ! -e "$ipdir"/"$2".ip ] &&  \
            echo "$0 $1 $2: file $ipdir/$2.ip not found" >&2 && exit 1
        [ ! -e "$ipdir"/dev ] && \
            echo "$0 $1: file $ipdir/dev not found" >&2 && exit 1
        ip=`cat "$ipdir/$2.ip"`
        dev=`cat "$ipdir/dev"`
        cn="$2"
        bwlimit-disable
        bwlimit-enable
        ;;
```

to:

```
      update)
        [ -z "$2" ] && echo "$0 $1: missing argument [client-CN]" >&2 && exit 1
        [ -z "$3" ] && echo "$0 $1 $2: missing argument [client-IP]" >&2 && exit 1
        [ ! -e "$ipdir"/"${2}-${3}".ip ] &&  \
            echo "$0 $1 $2: file $ipdir/${2}-${3}.ip not found" >&2 && exit 1
        [ ! -e "$ipdir"/dev ] && \
            echo "$0 $1: file $ipdir/dev not found" >&2 && exit 1
        ip=`cat "$ipdir/${2}-${3}.ip"`
        dev=`cat "$ipdir/dev"`
        cn="$2"
        bwlimit-disable
        bwlimit-enable
        ;;
```

> Side thought, when limiting per ip 50 unique people on 1 wifi network wold be throttled as 1 ip right? Any way you can think of where tc operates on a per-connection basis?

This depends on the setup, if the wifi network is behind a NAT, then all those clients will have the same IP address.

I think with `tc` you can only filter by IP addresses. At least I have no idea how this would be possible. Maybe in combination with `iptables`, which is aware of the connection states. But anyway if the clients are behind a NAT, there is no possibility to distinguish which connection belongs to which client from the outside. Only the device doing the NAT knows that information.

**Comment by DonZheng** [comment]
Hi @rda0 , sorry for jumping in an old thread.

I help my country fellows get through government censorship/firewall with OpenVPN. As most of them are not tech savvy, so I ship them apks with ovpn file pre-loaded. In other words, I also have this scenario where many users share the same openVPN Common Name 'client', except Admins who use a different CN 'admin'.

I do have issues that a small number of clients eating up most of bandwidth, so I would like to learn how to twist your script to suit my user case:
1. Limit each 'client' connection at 1.2Mbps
2. Limit each 'Admin' connection at 10Mbps

Could you please share some guidance?

It would be greatly appreciated.

===============
Server.conf looks like this:
port 1194
proto udp
dev tun
sndbuf 0
rcvbuf 0
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-auth ta.key 0
topology subnet
server 10.8.0.0 255.255.252.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
keepalive 10 120
cipher AES-128-CBC
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
verb 3
duplicate-cn
management localhost 7505
txqueuelen 1000
crl-verify crl.pem

Client.ovpn looks like this
client
dev tun
proto udp
sndbuf 0
rcvbuf 0
remote 198.71.55.116 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
auth SHA512
cipher AES-128-CBC
setenv opt block-outside-dns
key-direction 1
verb 3
<ca>

**Comment by rda0** [comment]
@DonZheng sorry for the late reply.

To do what you want, you need a class with the respective rate limit per IP address. Then you define matching filters to assign each IP address to a class.

I believe what you ask can be accomplished with the code changes mentioned in my last comment https://github.com/rda0/tc-openvpn/issues/2#issuecomment-332257643.

But since you only have 2 CNs and fixed rate limits it may also be a solution to define the TC rules statically (not using this script at all).

**Comment by rda0** [comment]
see also: https://gist.github.com/rda0/2edc01632578b0bd59b8c486f8a94989
